### PR TITLE
Update to v2.1.1

### PR DESCRIPTION
**Pull request by pedantic-git**
This pull request updates flatpickr_rails to the latest version of flatpickr, which adds support for localization, jQuery, more themes...

I also updated the README and removed an intentionally failing test.

Let me know if there are any concerns!

### CODE REVIEW

**Comment by jiren** [comment]
Thanks 👍

**Comment by pedantic-git** [comment]
Awesome! Please let me know when this has been pushed to rubygems.

Cheers!

**Comment by jiren** [comment]
Pushed to rubygems.

Thanks for PR.

**Comment by pedantic-git** [comment]
You're very welcome!

**Pull request merged**
